### ISSUE TITLE
Need help on: Getting access to the $mapObject inside mounted

### ISSUE THREAD

**Issue by hugohabicht01** [diegoazh/gmap-vue#176]
# What you try to do

I'm trying to access the $mapObject via this.$refs.googlemap.$mapObject (the name of my ref is googlemap) inside mounted(), where I have an event bus listener that should display directions when the event gets emmited.

# What is the problem
Accessing the $mapObject inside mounted fails, `Uncaught TypeError: Cannot read property '$mapObject' of undefined` is logged in the console

# What kind of things have you already treated
I tried wrapping it in this.$nextTick, as well as this.$refs.googlemap.$mapPromise. That didn't work and threw `vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in nextTick: "TypeError: _this.$refs.googlemap.$mapPromise is not a function"`. setTimeout didn't work either. I basically read https://stackoverflow.com/questions/54355375/vue-js-refs-are-undefined-even-though-this-refs-shows-theyre-there/58203295#58203295 and tried all suggested solutions, but none of them worked.

# Steps to reproduce

Try to access $mapObject from mounted

## Os

- [x] Arch Linux
- [x] Windows

## Mobile

- [x] Android

## Versions

- Node:v14.15.1
- NPM:6.14.8
- Yarn:1.22.10

## Package manager

- [ ] NPM
- [x] Yarn

## Plugin version

- [x] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by hugohabicht01** [comment]
Solved it by using vanilla js event listeners instead of vue event bus

**Comment by diegoazh** [comment]
Can you test the new version 2.0.0? I suspect that version has solved this issue.
It fails on mounted because you need to `await` for the promise resolve, you can read it in the [documentation](https://diegoazh.github.io/gmap-vue/#lazy-loading), I think that can help you, but as you marked the issue as solved I will close it but if you have any issue with version 2.0.0 feel free to open a new one.

Regards.
