### ISSUE TITLE
Need help on: How to implement localContext?

### ISSUE THREAD

**Issue by balabambe** [diegoazh/gmap-vue#179]
# What you try to do

I'm trying to use Local Context Library (now is in beta) to disable all place tag
![image](https://user-images.githubusercontent.com/51053024/125953115-dbc9990b-62d8-4c3a-b296-9c8cd1dfc336.png)
I want to hide these points.

# What is the problem

I want to implement `localContext` in `GmapMap`, but I don't know how to implement it.
I try to read all your documents, but none of describe them about `localContext`.

# What kind of things have you already treated

I was loaded the library as `localContext` in initialize parameters,
![image](https://user-images.githubusercontent.com/51053024/125953569-b7036ab3-9207-4b8a-b654-95429e1c2cda.png)
and success loaded `LocalContextMapView` in google map api ( `import {gmapApi} from 'gmap-vue'` ),
but next step I don't know how to implement this in my `GmapMap`.

I was read the document from google: https://developers.google.com/maps/documentation/javascript/local-context/migrate
but it seems must to replace original map instance.

So... next step is? how can I implement them? thanks a lot.

# Steps to reproduce

as above.

## Os

- [x] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: v14.17.2
- NPM: 7.19.1
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [x] 1.5.0
- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by diegoazh** [comment]
Thank you for reporting it, I will take a look at that.

**Comment by diegoazh** [comment]
The problem is that you need to replace the `Map` component itself `new google.maps.Map(...)` that will affect the entire plugin API, this fact and the beta state of this feature make it difficult to implement, on the other hand, I'm focused on stable features and migrate this plugin to Vue v3.
Maybe I could try some implementations but not right now, in the mind while you can try to use the `MapElementFactory` to build this new component and try to use it instead of using the `Map` component.
I hope the last suggestion will be useful.
Regards.

**Comment by balabambe** [comment]
Thanks for advice, I will try hard to implement. thanks.
