### ISSUE TITLE
Feature: Any Examples of Nearby Places?

### ISSUE THREAD

**Issue by adavie1** [diegoazh/gmap-vue#186]
API calls direct to the Google servers succeed. But digging a little deeper it seems can't call from axios or plain HTTP requests. Google API docs say the Places library is required.

I've got that in my settings but can't seem call the API.

**Comment by diegoazh** [comment]
Hi @adavie1 I don't understand well the problem I think, for the moment if you can test the new version 2.0.0 it will be useful, on the other hand, I will close the issue because it doesn't follow your issue template. I the problem persist please open a new one and I will try to help you, I'm restructuring the plugin and I will start the migration to Vue 3 and typescript the composition API will be useful in this plugin.

Regards.
