### ISSUE TITLE
Need help on: 

### ISSUE THREAD

**Issue by jasonloeve** [diegoazh/gmap-vue#202]
## What is the problem

tried setting this up in my build but im getting the following error

`Uncaught ReferenceError: exports is not defined`

## What kind of things have you already treated

Ive tried to include the full path which doesnt seem to help `import * as GmapVue from 'gmap-vue/dist/main'`

## Versions

- Node: v16.4.2
- NPM: 7.18.1

Using esbuild-vue: ^0.4.0

**Comment by diegoazh** [comment]
can you try with the new version 2.0.0 and try to use `import GmapVue from 'gmap-vue';` as you can see in [main.js](https://github.com/diegoazh/gmap-vue/blob/master/packages/gmap-vue/src/main.js) we are exporting by default the install function for the plugin and also two objects, `helpers` and `components` that is because you can register the plugin without components and only import and register the components that you will use in your app.
