### ISSUE TITLE
Need help on:  Unknown custom element: <gmap-map> - did you register the component correctly?

### ISSUE THREAD

**Issue by MinSomai** [diegoazh/gmap-vue#233]
## What you try to do

Install the plugin.

## What is the problem

I have been trying to install the plugin since yesterday and I have no idea where I've gone wrong. 

## What kind of things have you already treated

I have tried manually registering the components by having `installComponents: false` and with true too. I'll have my current setup below.

## Steps to reproduce

https://codesandbox.io/s/gmap-vue-mpwr7?file=/src/main.js

`main.js`

```js
import * as GmapVue from "gmap-vue";


console.log(GmapVue);

Vue.use(GmapVue, {
  load: {
    key: ""
  },
  installComponents: true
});

Vue.config.productionTip = false;

new Vue({
  router,
  vuetify,
  store,
  render: h => h(App)
}).$mount("#app");
```

```html
                  <gmap-map
                    :center="mapCenter"
                    :zoom="12"
                    ref="map"
                    class="map-container"
                    style="width: 500px; height: 300px"
                  ></gmap-map>
```

and the error

![component](https://user-images.githubusercontent.com/21338691/144359646-df711771-1830-490c-b22f-93d6cc185c60.jpg)

## Os

- [ ] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [x] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: v16.13.0
- NPM: 8.1.0
- Yarn:

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [x] 2.0.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by MinSomai** [comment]
I am using the version `2.0.2` of gmap-vue, and going down to `1.5.0` solved the issue. I'll assume version ^2 is for vue3.

**Comment by davydnorris** [comment]
No it's meant for the current version but @diegoazh made some packaging changes and it's been broken since. Rev back to 1.5 for now while we sort it out

**Comment by ShenWinnie** [comment]
`import * as GmapVue from "gmap-vue"` ;改为 `import GmapVue from "gmap-vue"`试试

**Comment by diegoazh** [comment]
@davydnorris are you still having issues?

**Comment by diegoazh** [comment]
@MinSomai, this plugin is for Vue 2 yet, we will start the migration to Vue 3 but currently works only on version 2.

**Comment by davydnorris** [comment]
> @davydnorris are you still having issues?

Hi @diegoazh - I've rolled back to 1.5 because the changes to drawing manager are breaking for me. 

This is a much more complex problem than it appears and the current code just doesn't work at all. The moment you copy the shapes array instead of using it directly, you not only lose the ability to pick up edits in the array, you also lose all reactivity on the original array.

My recommendation would be to put the direct array access back until we work out the simplest approach to properly implement this. At very least we need to:
 - add a deep watcher on the entire shapes array so that we can pick up changes made in the parent and reflect them in the drawing
 - emit events for additions, deletions and updates made by the manager, and avoid triggering the watcher if the parent makes the changes
 - work out how we treat and existing drawing options in the original shapes array. Should be honor them or override them with any passed in options?
 - work out how to properly treat shape highlighting, as discussed earlier

**Comment by pealthoff** [comment]
Hi @diegoazh , this problem is probably happening because people are following the documentation from the npm page, which is outdated in the way to import the library:
 (import * as VueGoogleMaps from 'gmap-vue') instead of (import GmapVue from 'gmap-vue')

it took me a few hours to realize this, maybe the npm page should only link to the official documentation

Thanks!

**Comment by amura11** [comment]
I ran into the same issue after upgrading from 1.5.0 using TypeScript. Using `import GmapVue from 'gmap-vue';` is the correct solution but in TypeScript you'll also need the a declaration file (at least I did). I ended up using the following declaration file:

**gmap-vue.d.ts**
```
declare module "gmap-vue" {
    import Vue, { PluginFunction } from "vue";

    const _default: { install(): PluginFunction<{}> };

    export default _default;

    export const components: {
        HeatmapLayer: typeof Vue;
        KmlLayer: typeof Vue;
        Marker: typeof Vue;
        Polyline: typeof Vue;
        Polygon: typeof Vue;
        Circle: typeof Vue;
        Cluster: typeof Vue;
        Rectangle: typeof Vue;
        DrawingManager: typeof Vue;
        InfoWindow: typeof Vue;
        MapLayer: typeof Vue;
        PlaceInput: typeof Vue;
        Autocomplete: typeof Vue;
        StreetViewPanorama: typeof Vue;
        MapElementMixin: typeof Vue;
        MountableMixin: typeof Vue;
    };
}
```

This lets you import and setup the library as expected (using `import GmapVue from 'gmap-vue';`), allows you to register components individually, eg:
```
import { components } from "gmap-vue";

Vue.component("Heatmap", components.HeatmapLayer)
```

And will play nicely with [Vue Class Component](https://class-component.vuejs.org/), eg:
```
import { components } from "gmap-vue";

@Component({ components: { "gmap-cluster": components.Cluster } })
```

P.S. I'm a noob with declaration files so this is probably wrong but it works just enough :D
