### ISSUE TITLE
Bug: Unexpected token error

### ISSUE THREAD

**Issue by bietkul** [diegoazh/gmap-vue#274]
> Please complete all sections that you can but please **don't remove any section**, otherwise the bot will close your issue because it doesn't meet our issue template (you can remove this comment)

## Describe the bug
We have upgraded it to v3.x and faced the unexpected token error because of optional chaining. It is important to fix this issue in library because we don't want our users to add additional configs.

- Either remove optional chaining
- or use `@babel/plugin-proposal-optional-chaining` plugin to transpile it.

## To reproduce

1. Go to 'Create a new vue 2.6 app using vue-cli'
2. Install  '.gmap-vue'
3. See error

## Expected behavior

It should work without an additional config.

## Current behavior

![alt error](https://i.imgur.com/mTZ3O9V.png)

## Versions

- Node:
- NPM:
- Yarn:

## Package manager

- [ ] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x

**Comment by davydnorris** [comment]
Yeah, this was put in by Diego and breaks on a lot of things - I've removed it in the latest code. A complete rewrite of the drawing manager is on its way

**Comment by bietkul** [comment]
Hello @davydnorris, is there any update?

**Comment by JavaChr1s** [comment]
@davydnorris any news here?

**Comment by davydnorris** [comment]
Still working on it - the new Drawing Manager is now a way to just draw new shapes. You are responsible for maintaining the array of shapes externally and the DM emits events with the new shape info. This was mostly straight forward except for polygons, which can have multiple paths to reflect internal holes.

 All that part is done and works well, but in the process of doing that I found numerous issues with all the shape components when they are put into edit or drag mode. I'm checking each one because I think the way they are built means the underlying google maps API mutates their properties but also turning on edit and drag causes an event storm and I'm trying to build something more robust around that. They were also inconsistent in how they handled path arrays, which can be an Array or an MVCArray object

There's also a lot of value in having a generic Shape component with a shapeType property and I'm looking at this. Right now if you have an array of drawn shapes you end up with a great big block of v-if... v-elseif in your map code, which is not nice

**Comment by davydnorris** [comment]
@bietkul unfortunately I don't have the ability to accept changes into the repo. Only @diegoazh can do that

**Comment by diegoazh** [comment]
@bietkul can you test if the `@babel/preset-env` is working as expected? The babel documentation said that the `@babel/plugin-proposal-optional-chaining` plugin is included on the `@babel/preset-env`, I recently noted that on the `.babelrc` file we were using the old `@babel/env` instead of `@babel/preset-env`, my bad sorry.

**Comment by bietkul** [comment]
Yes, it works with Vue template, but doesn't work with `Nuxt`.
It is best to fix the issue in `gmap-vue` library.

**Comment by bietkul** [comment]
@diegoazh I've raised a PR, can you review and release a new version.
