### ISSUE TITLE
Need help on: TypeScript Declaration File Missing for @gmap-vue/v3

### ISSUE THREAD

**Issue by lunpessoa** [diegoazh/gmap-vue#307]
## What you try to do

I am attempting to integrate the @gmap-vue/v3 library into my TypeScript project to enable Google Maps functionality.

## What is the problem

The TypeScript compiler is failing to locate the declaration file for the module '@gmap-vue/v3'. The error message indicates that the file 'project/node_modules/@gmap-vue/v3/dist/main.es.js' implicitly has an 'any' type, even though there are types available at 'node_modules/@gmap-vue/v3/dist/types/src/main.d.ts'.

## What kind of things have you already treated

I have verified the correctness of the path specified in the "typings" field of the package.json. I have also updated TypeScript to the latest version, but the issue persists.

## Steps to reproduce

To reproduce the issue:
1. Install the @gmap-vue/v3 library in a TypeScript project.
2. Attempt to import the module in a TypeScript file.
3. Observe the TypeScript error regarding the missing declaration file.

## OS

- [x] Mac Os X
- [ ] Linux (write here the name and version of your distribution)
- [ ] Windows

## Mobile

- [ ] iOS
- [ ] Android

## Versions

- Node: v18.16.1
- NPM:  v9.5.1
- Yarn: 

## Package manager

- [x] NPM
- [ ] Yarn

## Plugin version

- [ ] 1.4.x
- [ ] 1.2.x
- [ ] 1.0.x
- [x] gmv3_v1.0.3

**Comment by basuneko** [comment]
@lunpessoa I've also had this issue. I think the types' exports may be a little crooked and don't work great with some TS configurations. I've found that only `moduleResolution: node` more-or-less works out of the box; `moduleResolution: bundler` gives the same error you've shared (likely because `resolvePackageJsonExports` is true in this mode).

```
The TypeScript compiler is failing to locate the declaration file for the module '@gmap-vue/v3'. The error message indicates that the file 'project/node_modules/@gmap-vue/v3/dist/main.es.js' implicitly has an 'any' type, even though there are types available at 'node_modules/@gmap-vue/v3/dist/types/src/main.d.ts'.
```

As a workaround, I've managed to fix this issue by adding the `types` entry to the package.json's exports:
```diff
diff --git a/node_modules/@gmap-vue/v3/package.json b/node_modules/@gmap-vue/v3/package.json
  "exports": {
     ".": {
+      "types": "./dist/types/src/main.d.ts"
       "import": "./dist/main.es.js",
       "require": "./dist/main.umd.js",
       "default": "./dist/main.es.js"
     }
   },
```

For the time being, I'm using [patch-package](https://www.npmjs.com/package/patch-package); however, it would be nice to merge this into the repo.

**Comment by diegoazh** [comment]
A new version is coming soon, with breaking changes, but with a big improvement in the plugin API and its types 💪🏼.

**Comment by diegoazh** [comment]
I'm going to close this but, if you find something wrong related to this ticket feel free to re-open it or open a new one if you discover something new. Thank you.
